name: "Grocy"
description: "Grocy - ERP beyond your fridge. Groceries & household management."
version: "1.1.0"
slug: "grocy_linuxserver"
init: false
arch:
  - aarch64
  - amd64
startup: services
boot: auto
ports:
  80/tcp: 9283
ports_description:
  80/tcp: "Grocy Web UI & API"
ingress: true
ingress_port: 80
ingress_stream: false
map:
  - type: config
    path: /config
    read_only: false
options:
  culture: de
  currency: EUR
  entry_page: stock
  grocycode_type: 2D
  features:
    batteries: false
    calendar: true
    chores: true
    equipment: false
    recipes: true
    shoppinglist: true
    stock: true
    tasks: false
  tweaks:
    chores_assignment: true
    multiple_shopping_lists: true
    stock_best_before_date_tracking: true
    stock_location_tracking: true
    stock_price_tracking: true
    stock_product_freezing: true
    stock_product_opened_tracking: true
    stock_count_opened_products_against_minimum_stock_amount: true
schema:
  culture: str
  currency: str
  entry_page: str
  grocycode_type: str
  features:
    batteries: bool
    calendar: bool
    chores: bool
    equipment: bool
    recipes: bool
    shoppinglist: bool
    stock: bool
    tasks: bool
  tweaks:
    chores_assignment: bool
    multiple_shopping_lists: bool
    stock_best_before_date_tracking: bool
    stock_location_tracking: bool
    stock_price_tracking: bool
    stock_product_freezing: bool
    stock_product_opened_tracking: bool
    stock_count_opened_products_against_minimum_stock_amount: bool
