name: "MCP GitHub"
description: "Official GitHub MCP Server extended with binary file support via Model Context Protocol."
version: "1.5.3"
slug: "mcp_github"
init: false
arch:
  - amd64
startup: services
boot: auto
ports:
  8766/tcp: 8766
map:
  - config:rw
options:
  github_token: ""
schema:
  github_token: str
